db:
  image: postgres
  ports:
    - "5432"
web:
  build: .
  entrypoint:
    - env
    - --unset=RAILS_ENV
  command: bundle exec puma -C config/puma.rb
  volumes:
    - .:/usr/src/howse
  volumes_from:
    - bundle
  ports:
    - "3000:3000"
  links:
    - db
bundle:
  image: howse_web
  command: echo Done
  volumes:
    - /bundle
